/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CarerRouteRouteImport } from './routes/carer/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarerIndexRouteImport } from './routes/carer/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DocumentsSlugRouteImport } from './routes/documents.$slug'
import { Route as CarerShiftsRouteImport } from './routes/carer/shifts'
import { Route as CarerProfileRouteImport } from './routes/carer/profile'
import { Route as CarerLoginRouteImport } from './routes/carer/login'
import { Route as CarerForgotPasswordRouteImport } from './routes/carer/forgot-password'
import { Route as CarerDocumentsRouteImport } from './routes/carer/documents'
import { Route as CarerAvailabilityRouteImport } from './routes/carer/availability'
import { Route as AuthChangePasswordRouteImport } from './routes/auth/change-password'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedShiftsRouteImport } from './routes/_authenticated/shifts'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCentresRouteImport } from './routes/_authenticated/centres'
import { Route as AuthenticatedAvailabilityRouteImport } from './routes/_authenticated/availability'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as CarerOnboardingRouteRouteImport } from './routes/carer/onboarding/route'
import { Route as CarerShiftsIndexRouteImport } from './routes/carer/shifts.index'
import { Route as CarerOnboardingIndexRouteImport } from './routes/carer/onboarding/index'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff.index'
import { Route as AuthenticatedShiftsIndexRouteImport } from './routes/_authenticated/shifts.index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedCentresIndexRouteImport } from './routes/_authenticated/centres.index'
import { Route as CarerShiftsIdRouteImport } from './routes/carer/shifts.$id'
import { Route as CarerResetPasswordTokenRouteImport } from './routes/carer/reset-password.$token'
import { Route as CarerOnboardingProfileRouteImport } from './routes/carer/onboarding/profile'
import { Route as CarerOnboardingDocumentsRouteImport } from './routes/carer/onboarding/documents'
import { Route as CarerOnboardingAvailabilityRouteImport } from './routes/carer/onboarding/availability'
import { Route as CarerInviteTokenRouteImport } from './routes/carer/invite.$token'
import { Route as AuthenticatedStaffNewRouteImport } from './routes/_authenticated/staff.new'
import { Route as AuthenticatedStaffImportRouteImport } from './routes/_authenticated/staff.import'
import { Route as AuthenticatedStaffIdRouteImport } from './routes/_authenticated/staff.$id'
import { Route as AuthenticatedShiftsNewRouteImport } from './routes/_authenticated/shifts.new'
import { Route as AuthenticatedShiftsIdRouteImport } from './routes/_authenticated/shifts.$id'
import { Route as AuthenticatedReportsStaffUsageRouteImport } from './routes/_authenticated/reports.staff-usage'
import { Route as AuthenticatedReportsShiftFulfillmentRouteImport } from './routes/_authenticated/reports.shift-fulfillment'
import { Route as AuthenticatedReportsDocumentsRouteImport } from './routes/_authenticated/reports.documents'
import { Route as AuthenticatedReportsCentreUsageRouteImport } from './routes/_authenticated/reports.centre-usage'
import { Route as AuthenticatedReportsActivityRouteImport } from './routes/_authenticated/reports.activity'
import { Route as AuthenticatedCentresNewRouteImport } from './routes/_authenticated/centres.new'
import { Route as AuthenticatedCentresIdRouteImport } from './routes/_authenticated/centres.$id'

const CarerRouteRoute = CarerRouteRouteImport.update({
  id: '/carer',
  path: '/carer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarerIndexRoute = CarerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarerRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DocumentsSlugRoute = DocumentsSlugRouteImport.update({
  id: '/documents/$slug',
  path: '/documents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CarerShiftsRoute = CarerShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => CarerRouteRoute,
} as any)
const CarerProfileRoute = CarerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CarerRouteRoute,
} as any)
const CarerLoginRoute = CarerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CarerRouteRoute,
} as any)
const CarerForgotPasswordRoute = CarerForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => CarerRouteRoute,
} as any)
const CarerDocumentsRoute = CarerDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => CarerRouteRoute,
} as any)
const CarerAvailabilityRoute = CarerAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => CarerRouteRoute,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShiftsRoute = AuthenticatedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCentresRoute = AuthenticatedCentresRouteImport.update({
  id: '/centres',
  path: '/centres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvailabilityRoute =
  AuthenticatedAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const CarerOnboardingRouteRoute = CarerOnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => CarerRouteRoute,
} as any)
const CarerShiftsIndexRoute = CarerShiftsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarerShiftsRoute,
} as any)
const CarerOnboardingIndexRoute = CarerOnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarerOnboardingRouteRoute,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedShiftsIndexRoute =
  AuthenticatedShiftsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedShiftsRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedCentresIndexRoute =
  AuthenticatedCentresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCentresRoute,
  } as any)
const CarerShiftsIdRoute = CarerShiftsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CarerShiftsRoute,
} as any)
const CarerResetPasswordTokenRoute = CarerResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => CarerRouteRoute,
} as any)
const CarerOnboardingProfileRoute = CarerOnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CarerOnboardingRouteRoute,
} as any)
const CarerOnboardingDocumentsRoute =
  CarerOnboardingDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => CarerOnboardingRouteRoute,
  } as any)
const CarerOnboardingAvailabilityRoute =
  CarerOnboardingAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => CarerOnboardingRouteRoute,
  } as any)
const CarerInviteTokenRoute = CarerInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => CarerRouteRoute,
} as any)
const AuthenticatedStaffNewRoute = AuthenticatedStaffNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedStaffImportRoute =
  AuthenticatedStaffImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffIdRoute = AuthenticatedStaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedShiftsNewRoute = AuthenticatedShiftsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedShiftsRoute,
} as any)
const AuthenticatedShiftsIdRoute = AuthenticatedShiftsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedShiftsRoute,
} as any)
const AuthenticatedReportsStaffUsageRoute =
  AuthenticatedReportsStaffUsageRouteImport.update({
    id: '/staff-usage',
    path: '/staff-usage',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsShiftFulfillmentRoute =
  AuthenticatedReportsShiftFulfillmentRouteImport.update({
    id: '/shift-fulfillment',
    path: '/shift-fulfillment',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsDocumentsRoute =
  AuthenticatedReportsDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsCentreUsageRoute =
  AuthenticatedReportsCentreUsageRouteImport.update({
    id: '/centre-usage',
    path: '/centre-usage',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsActivityRoute =
  AuthenticatedReportsActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedCentresNewRoute = AuthenticatedCentresNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedCentresRoute,
} as any)
const AuthenticatedCentresIdRoute = AuthenticatedCentresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCentresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/carer': typeof CarerRouteRouteWithChildren
  '/carer/onboarding': typeof CarerOnboardingRouteRouteWithChildren
  '/applications': typeof AuthenticatedApplicationsRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/centres': typeof AuthenticatedCentresRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/shifts': typeof AuthenticatedShiftsRouteWithChildren
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/carer/availability': typeof CarerAvailabilityRoute
  '/carer/documents': typeof CarerDocumentsRoute
  '/carer/forgot-password': typeof CarerForgotPasswordRoute
  '/carer/login': typeof CarerLoginRoute
  '/carer/profile': typeof CarerProfileRoute
  '/carer/shifts': typeof CarerShiftsRouteWithChildren
  '/documents/$slug': typeof DocumentsSlugRoute
  '/auth/': typeof AuthIndexRoute
  '/carer/': typeof CarerIndexRoute
  '/centres/$id': typeof AuthenticatedCentresIdRoute
  '/centres/new': typeof AuthenticatedCentresNewRoute
  '/reports/activity': typeof AuthenticatedReportsActivityRoute
  '/reports/centre-usage': typeof AuthenticatedReportsCentreUsageRoute
  '/reports/documents': typeof AuthenticatedReportsDocumentsRoute
  '/reports/shift-fulfillment': typeof AuthenticatedReportsShiftFulfillmentRoute
  '/reports/staff-usage': typeof AuthenticatedReportsStaffUsageRoute
  '/shifts/$id': typeof AuthenticatedShiftsIdRoute
  '/shifts/new': typeof AuthenticatedShiftsNewRoute
  '/staff/$id': typeof AuthenticatedStaffIdRoute
  '/staff/import': typeof AuthenticatedStaffImportRoute
  '/staff/new': typeof AuthenticatedStaffNewRoute
  '/carer/invite/$token': typeof CarerInviteTokenRoute
  '/carer/onboarding/availability': typeof CarerOnboardingAvailabilityRoute
  '/carer/onboarding/documents': typeof CarerOnboardingDocumentsRoute
  '/carer/onboarding/profile': typeof CarerOnboardingProfileRoute
  '/carer/reset-password/$token': typeof CarerResetPasswordTokenRoute
  '/carer/shifts/$id': typeof CarerShiftsIdRoute
  '/centres/': typeof AuthenticatedCentresIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/shifts/': typeof AuthenticatedShiftsIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/carer/onboarding/': typeof CarerOnboardingIndexRoute
  '/carer/shifts/': typeof CarerShiftsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/users': typeof AuthenticatedUsersRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/carer/availability': typeof CarerAvailabilityRoute
  '/carer/documents': typeof CarerDocumentsRoute
  '/carer/forgot-password': typeof CarerForgotPasswordRoute
  '/carer/login': typeof CarerLoginRoute
  '/carer/profile': typeof CarerProfileRoute
  '/documents/$slug': typeof DocumentsSlugRoute
  '/auth': typeof AuthIndexRoute
  '/carer': typeof CarerIndexRoute
  '/centres/$id': typeof AuthenticatedCentresIdRoute
  '/centres/new': typeof AuthenticatedCentresNewRoute
  '/reports/activity': typeof AuthenticatedReportsActivityRoute
  '/reports/centre-usage': typeof AuthenticatedReportsCentreUsageRoute
  '/reports/documents': typeof AuthenticatedReportsDocumentsRoute
  '/reports/shift-fulfillment': typeof AuthenticatedReportsShiftFulfillmentRoute
  '/reports/staff-usage': typeof AuthenticatedReportsStaffUsageRoute
  '/shifts/$id': typeof AuthenticatedShiftsIdRoute
  '/shifts/new': typeof AuthenticatedShiftsNewRoute
  '/staff/$id': typeof AuthenticatedStaffIdRoute
  '/staff/import': typeof AuthenticatedStaffImportRoute
  '/staff/new': typeof AuthenticatedStaffNewRoute
  '/carer/invite/$token': typeof CarerInviteTokenRoute
  '/carer/onboarding/availability': typeof CarerOnboardingAvailabilityRoute
  '/carer/onboarding/documents': typeof CarerOnboardingDocumentsRoute
  '/carer/onboarding/profile': typeof CarerOnboardingProfileRoute
  '/carer/reset-password/$token': typeof CarerResetPasswordTokenRoute
  '/carer/shifts/$id': typeof CarerShiftsIdRoute
  '/centres': typeof AuthenticatedCentresIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/shifts': typeof AuthenticatedShiftsIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/carer/onboarding': typeof CarerOnboardingIndexRoute
  '/carer/shifts': typeof CarerShiftsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/carer': typeof CarerRouteRouteWithChildren
  '/carer/onboarding': typeof CarerOnboardingRouteRouteWithChildren
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/availability': typeof AuthenticatedAvailabilityRoute
  '/_authenticated/centres': typeof AuthenticatedCentresRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/shifts': typeof AuthenticatedShiftsRouteWithChildren
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/carer/availability': typeof CarerAvailabilityRoute
  '/carer/documents': typeof CarerDocumentsRoute
  '/carer/forgot-password': typeof CarerForgotPasswordRoute
  '/carer/login': typeof CarerLoginRoute
  '/carer/profile': typeof CarerProfileRoute
  '/carer/shifts': typeof CarerShiftsRouteWithChildren
  '/documents/$slug': typeof DocumentsSlugRoute
  '/auth/': typeof AuthIndexRoute
  '/carer/': typeof CarerIndexRoute
  '/_authenticated/centres/$id': typeof AuthenticatedCentresIdRoute
  '/_authenticated/centres/new': typeof AuthenticatedCentresNewRoute
  '/_authenticated/reports/activity': typeof AuthenticatedReportsActivityRoute
  '/_authenticated/reports/centre-usage': typeof AuthenticatedReportsCentreUsageRoute
  '/_authenticated/reports/documents': typeof AuthenticatedReportsDocumentsRoute
  '/_authenticated/reports/shift-fulfillment': typeof AuthenticatedReportsShiftFulfillmentRoute
  '/_authenticated/reports/staff-usage': typeof AuthenticatedReportsStaffUsageRoute
  '/_authenticated/shifts/$id': typeof AuthenticatedShiftsIdRoute
  '/_authenticated/shifts/new': typeof AuthenticatedShiftsNewRoute
  '/_authenticated/staff/$id': typeof AuthenticatedStaffIdRoute
  '/_authenticated/staff/import': typeof AuthenticatedStaffImportRoute
  '/_authenticated/staff/new': typeof AuthenticatedStaffNewRoute
  '/carer/invite/$token': typeof CarerInviteTokenRoute
  '/carer/onboarding/availability': typeof CarerOnboardingAvailabilityRoute
  '/carer/onboarding/documents': typeof CarerOnboardingDocumentsRoute
  '/carer/onboarding/profile': typeof CarerOnboardingProfileRoute
  '/carer/reset-password/$token': typeof CarerResetPasswordTokenRoute
  '/carer/shifts/$id': typeof CarerShiftsIdRoute
  '/_authenticated/centres/': typeof AuthenticatedCentresIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/shifts/': typeof AuthenticatedShiftsIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/carer/onboarding/': typeof CarerOnboardingIndexRoute
  '/carer/shifts/': typeof CarerShiftsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carer'
    | '/carer/onboarding'
    | '/applications'
    | '/availability'
    | '/centres'
    | '/dashboard'
    | '/profile'
    | '/reports'
    | '/shifts'
    | '/staff'
    | '/users'
    | '/auth/change-password'
    | '/carer/availability'
    | '/carer/documents'
    | '/carer/forgot-password'
    | '/carer/login'
    | '/carer/profile'
    | '/carer/shifts'
    | '/documents/$slug'
    | '/auth/'
    | '/carer/'
    | '/centres/$id'
    | '/centres/new'
    | '/reports/activity'
    | '/reports/centre-usage'
    | '/reports/documents'
    | '/reports/shift-fulfillment'
    | '/reports/staff-usage'
    | '/shifts/$id'
    | '/shifts/new'
    | '/staff/$id'
    | '/staff/import'
    | '/staff/new'
    | '/carer/invite/$token'
    | '/carer/onboarding/availability'
    | '/carer/onboarding/documents'
    | '/carer/onboarding/profile'
    | '/carer/reset-password/$token'
    | '/carer/shifts/$id'
    | '/centres/'
    | '/reports/'
    | '/shifts/'
    | '/staff/'
    | '/carer/onboarding/'
    | '/carer/shifts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/availability'
    | '/dashboard'
    | '/profile'
    | '/users'
    | '/auth/change-password'
    | '/carer/availability'
    | '/carer/documents'
    | '/carer/forgot-password'
    | '/carer/login'
    | '/carer/profile'
    | '/documents/$slug'
    | '/auth'
    | '/carer'
    | '/centres/$id'
    | '/centres/new'
    | '/reports/activity'
    | '/reports/centre-usage'
    | '/reports/documents'
    | '/reports/shift-fulfillment'
    | '/reports/staff-usage'
    | '/shifts/$id'
    | '/shifts/new'
    | '/staff/$id'
    | '/staff/import'
    | '/staff/new'
    | '/carer/invite/$token'
    | '/carer/onboarding/availability'
    | '/carer/onboarding/documents'
    | '/carer/onboarding/profile'
    | '/carer/reset-password/$token'
    | '/carer/shifts/$id'
    | '/centres'
    | '/reports'
    | '/shifts'
    | '/staff'
    | '/carer/onboarding'
    | '/carer/shifts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/carer'
    | '/carer/onboarding'
    | '/_authenticated/applications'
    | '/_authenticated/availability'
    | '/_authenticated/centres'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/shifts'
    | '/_authenticated/staff'
    | '/_authenticated/users'
    | '/auth/change-password'
    | '/carer/availability'
    | '/carer/documents'
    | '/carer/forgot-password'
    | '/carer/login'
    | '/carer/profile'
    | '/carer/shifts'
    | '/documents/$slug'
    | '/auth/'
    | '/carer/'
    | '/_authenticated/centres/$id'
    | '/_authenticated/centres/new'
    | '/_authenticated/reports/activity'
    | '/_authenticated/reports/centre-usage'
    | '/_authenticated/reports/documents'
    | '/_authenticated/reports/shift-fulfillment'
    | '/_authenticated/reports/staff-usage'
    | '/_authenticated/shifts/$id'
    | '/_authenticated/shifts/new'
    | '/_authenticated/staff/$id'
    | '/_authenticated/staff/import'
    | '/_authenticated/staff/new'
    | '/carer/invite/$token'
    | '/carer/onboarding/availability'
    | '/carer/onboarding/documents'
    | '/carer/onboarding/profile'
    | '/carer/reset-password/$token'
    | '/carer/shifts/$id'
    | '/_authenticated/centres/'
    | '/_authenticated/reports/'
    | '/_authenticated/shifts/'
    | '/_authenticated/staff/'
    | '/carer/onboarding/'
    | '/carer/shifts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CarerRouteRoute: typeof CarerRouteRouteWithChildren
  DocumentsSlugRoute: typeof DocumentsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/carer': {
      id: '/carer'
      path: '/carer'
      fullPath: '/carer'
      preLoaderRoute: typeof CarerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carer/': {
      id: '/carer/'
      path: '/'
      fullPath: '/carer/'
      preLoaderRoute: typeof CarerIndexRouteImport
      parentRoute: typeof CarerRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/documents/$slug': {
      id: '/documents/$slug'
      path: '/documents/$slug'
      fullPath: '/documents/$slug'
      preLoaderRoute: typeof DocumentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carer/shifts': {
      id: '/carer/shifts'
      path: '/shifts'
      fullPath: '/carer/shifts'
      preLoaderRoute: typeof CarerShiftsRouteImport
      parentRoute: typeof CarerRouteRoute
    }
    '/carer/profile': {
      id: '/carer/profile'
      path: '/profile'
      fullPath: '/carer/profile'
      preLoaderRoute: typeof CarerProfileRouteImport
      parentRoute: typeof CarerRouteRoute
    }
    '/carer/login': {
      id: '/carer/login'
      path: '/login'
      fullPath: '/carer/login'
      preLoaderRoute: typeof CarerLoginRouteImport
      parentRoute: typeof CarerRouteRoute
    }
    '/carer/forgot-password': {
      id: '/carer/forgot-password'
      path: '/forgot-password'
      fullPath: '/carer/forgot-password'
      preLoaderRoute: typeof CarerForgotPasswordRouteImport
      parentRoute: typeof CarerRouteRoute
    }
    '/carer/documents': {
      id: '/carer/documents'
      path: '/documents'
      fullPath: '/carer/documents'
      preLoaderRoute: typeof CarerDocumentsRouteImport
      parentRoute: typeof CarerRouteRoute
    }
    '/carer/availability': {
      id: '/carer/availability'
      path: '/availability'
      fullPath: '/carer/availability'
      preLoaderRoute: typeof CarerAvailabilityRouteImport
      parentRoute: typeof CarerRouteRoute
    }
    '/auth/change-password': {
      id: '/auth/change-password'
      path: '/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shifts': {
      id: '/_authenticated/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthenticatedShiftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/centres': {
      id: '/_authenticated/centres'
      path: '/centres'
      fullPath: '/centres'
      preLoaderRoute: typeof AuthenticatedCentresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/availability': {
      id: '/_authenticated/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AuthenticatedAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/carer/onboarding': {
      id: '/carer/onboarding'
      path: '/onboarding'
      fullPath: '/carer/onboarding'
      preLoaderRoute: typeof CarerOnboardingRouteRouteImport
      parentRoute: typeof CarerRouteRoute
    }
    '/carer/shifts/': {
      id: '/carer/shifts/'
      path: '/'
      fullPath: '/carer/shifts/'
      preLoaderRoute: typeof CarerShiftsIndexRouteImport
      parentRoute: typeof CarerShiftsRoute
    }
    '/carer/onboarding/': {
      id: '/carer/onboarding/'
      path: '/'
      fullPath: '/carer/onboarding/'
      preLoaderRoute: typeof CarerOnboardingIndexRouteImport
      parentRoute: typeof CarerOnboardingRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/shifts/': {
      id: '/_authenticated/shifts/'
      path: '/'
      fullPath: '/shifts/'
      preLoaderRoute: typeof AuthenticatedShiftsIndexRouteImport
      parentRoute: typeof AuthenticatedShiftsRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/centres/': {
      id: '/_authenticated/centres/'
      path: '/'
      fullPath: '/centres/'
      preLoaderRoute: typeof AuthenticatedCentresIndexRouteImport
      parentRoute: typeof AuthenticatedCentresRoute
    }
    '/carer/shifts/$id': {
      id: '/carer/shifts/$id'
      path: '/$id'
      fullPath: '/carer/shifts/$id'
      preLoaderRoute: typeof CarerShiftsIdRouteImport
      parentRoute: typeof CarerShiftsRoute
    }
    '/carer/reset-password/$token': {
      id: '/carer/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/carer/reset-password/$token'
      preLoaderRoute: typeof CarerResetPasswordTokenRouteImport
      parentRoute: typeof CarerRouteRoute
    }
    '/carer/onboarding/profile': {
      id: '/carer/onboarding/profile'
      path: '/profile'
      fullPath: '/carer/onboarding/profile'
      preLoaderRoute: typeof CarerOnboardingProfileRouteImport
      parentRoute: typeof CarerOnboardingRouteRoute
    }
    '/carer/onboarding/documents': {
      id: '/carer/onboarding/documents'
      path: '/documents'
      fullPath: '/carer/onboarding/documents'
      preLoaderRoute: typeof CarerOnboardingDocumentsRouteImport
      parentRoute: typeof CarerOnboardingRouteRoute
    }
    '/carer/onboarding/availability': {
      id: '/carer/onboarding/availability'
      path: '/availability'
      fullPath: '/carer/onboarding/availability'
      preLoaderRoute: typeof CarerOnboardingAvailabilityRouteImport
      parentRoute: typeof CarerOnboardingRouteRoute
    }
    '/carer/invite/$token': {
      id: '/carer/invite/$token'
      path: '/invite/$token'
      fullPath: '/carer/invite/$token'
      preLoaderRoute: typeof CarerInviteTokenRouteImport
      parentRoute: typeof CarerRouteRoute
    }
    '/_authenticated/staff/new': {
      id: '/_authenticated/staff/new'
      path: '/new'
      fullPath: '/staff/new'
      preLoaderRoute: typeof AuthenticatedStaffNewRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/import': {
      id: '/_authenticated/staff/import'
      path: '/import'
      fullPath: '/staff/import'
      preLoaderRoute: typeof AuthenticatedStaffImportRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/$id': {
      id: '/_authenticated/staff/$id'
      path: '/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof AuthenticatedStaffIdRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/shifts/new': {
      id: '/_authenticated/shifts/new'
      path: '/new'
      fullPath: '/shifts/new'
      preLoaderRoute: typeof AuthenticatedShiftsNewRouteImport
      parentRoute: typeof AuthenticatedShiftsRoute
    }
    '/_authenticated/shifts/$id': {
      id: '/_authenticated/shifts/$id'
      path: '/$id'
      fullPath: '/shifts/$id'
      preLoaderRoute: typeof AuthenticatedShiftsIdRouteImport
      parentRoute: typeof AuthenticatedShiftsRoute
    }
    '/_authenticated/reports/staff-usage': {
      id: '/_authenticated/reports/staff-usage'
      path: '/staff-usage'
      fullPath: '/reports/staff-usage'
      preLoaderRoute: typeof AuthenticatedReportsStaffUsageRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/shift-fulfillment': {
      id: '/_authenticated/reports/shift-fulfillment'
      path: '/shift-fulfillment'
      fullPath: '/reports/shift-fulfillment'
      preLoaderRoute: typeof AuthenticatedReportsShiftFulfillmentRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/documents': {
      id: '/_authenticated/reports/documents'
      path: '/documents'
      fullPath: '/reports/documents'
      preLoaderRoute: typeof AuthenticatedReportsDocumentsRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/centre-usage': {
      id: '/_authenticated/reports/centre-usage'
      path: '/centre-usage'
      fullPath: '/reports/centre-usage'
      preLoaderRoute: typeof AuthenticatedReportsCentreUsageRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/activity': {
      id: '/_authenticated/reports/activity'
      path: '/activity'
      fullPath: '/reports/activity'
      preLoaderRoute: typeof AuthenticatedReportsActivityRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/centres/new': {
      id: '/_authenticated/centres/new'
      path: '/new'
      fullPath: '/centres/new'
      preLoaderRoute: typeof AuthenticatedCentresNewRouteImport
      parentRoute: typeof AuthenticatedCentresRoute
    }
    '/_authenticated/centres/$id': {
      id: '/_authenticated/centres/$id'
      path: '/$id'
      fullPath: '/centres/$id'
      preLoaderRoute: typeof AuthenticatedCentresIdRouteImport
      parentRoute: typeof AuthenticatedCentresRoute
    }
  }
}

interface AuthenticatedCentresRouteChildren {
  AuthenticatedCentresIdRoute: typeof AuthenticatedCentresIdRoute
  AuthenticatedCentresNewRoute: typeof AuthenticatedCentresNewRoute
  AuthenticatedCentresIndexRoute: typeof AuthenticatedCentresIndexRoute
}

const AuthenticatedCentresRouteChildren: AuthenticatedCentresRouteChildren = {
  AuthenticatedCentresIdRoute: AuthenticatedCentresIdRoute,
  AuthenticatedCentresNewRoute: AuthenticatedCentresNewRoute,
  AuthenticatedCentresIndexRoute: AuthenticatedCentresIndexRoute,
}

const AuthenticatedCentresRouteWithChildren =
  AuthenticatedCentresRoute._addFileChildren(AuthenticatedCentresRouteChildren)

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsActivityRoute: typeof AuthenticatedReportsActivityRoute
  AuthenticatedReportsCentreUsageRoute: typeof AuthenticatedReportsCentreUsageRoute
  AuthenticatedReportsDocumentsRoute: typeof AuthenticatedReportsDocumentsRoute
  AuthenticatedReportsShiftFulfillmentRoute: typeof AuthenticatedReportsShiftFulfillmentRoute
  AuthenticatedReportsStaffUsageRoute: typeof AuthenticatedReportsStaffUsageRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsActivityRoute: AuthenticatedReportsActivityRoute,
  AuthenticatedReportsCentreUsageRoute: AuthenticatedReportsCentreUsageRoute,
  AuthenticatedReportsDocumentsRoute: AuthenticatedReportsDocumentsRoute,
  AuthenticatedReportsShiftFulfillmentRoute:
    AuthenticatedReportsShiftFulfillmentRoute,
  AuthenticatedReportsStaffUsageRoute: AuthenticatedReportsStaffUsageRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedShiftsRouteChildren {
  AuthenticatedShiftsIdRoute: typeof AuthenticatedShiftsIdRoute
  AuthenticatedShiftsNewRoute: typeof AuthenticatedShiftsNewRoute
  AuthenticatedShiftsIndexRoute: typeof AuthenticatedShiftsIndexRoute
}

const AuthenticatedShiftsRouteChildren: AuthenticatedShiftsRouteChildren = {
  AuthenticatedShiftsIdRoute: AuthenticatedShiftsIdRoute,
  AuthenticatedShiftsNewRoute: AuthenticatedShiftsNewRoute,
  AuthenticatedShiftsIndexRoute: AuthenticatedShiftsIndexRoute,
}

const AuthenticatedShiftsRouteWithChildren =
  AuthenticatedShiftsRoute._addFileChildren(AuthenticatedShiftsRouteChildren)

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffIdRoute: typeof AuthenticatedStaffIdRoute
  AuthenticatedStaffImportRoute: typeof AuthenticatedStaffImportRoute
  AuthenticatedStaffNewRoute: typeof AuthenticatedStaffNewRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffIdRoute: AuthenticatedStaffIdRoute,
  AuthenticatedStaffImportRoute: AuthenticatedStaffImportRoute,
  AuthenticatedStaffNewRoute: AuthenticatedStaffNewRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedAvailabilityRoute: typeof AuthenticatedAvailabilityRoute
  AuthenticatedCentresRoute: typeof AuthenticatedCentresRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedShiftsRoute: typeof AuthenticatedShiftsRouteWithChildren
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedAvailabilityRoute: AuthenticatedAvailabilityRoute,
  AuthenticatedCentresRoute: AuthenticatedCentresRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedShiftsRoute: AuthenticatedShiftsRouteWithChildren,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface CarerOnboardingRouteRouteChildren {
  CarerOnboardingAvailabilityRoute: typeof CarerOnboardingAvailabilityRoute
  CarerOnboardingDocumentsRoute: typeof CarerOnboardingDocumentsRoute
  CarerOnboardingProfileRoute: typeof CarerOnboardingProfileRoute
  CarerOnboardingIndexRoute: typeof CarerOnboardingIndexRoute
}

const CarerOnboardingRouteRouteChildren: CarerOnboardingRouteRouteChildren = {
  CarerOnboardingAvailabilityRoute: CarerOnboardingAvailabilityRoute,
  CarerOnboardingDocumentsRoute: CarerOnboardingDocumentsRoute,
  CarerOnboardingProfileRoute: CarerOnboardingProfileRoute,
  CarerOnboardingIndexRoute: CarerOnboardingIndexRoute,
}

const CarerOnboardingRouteRouteWithChildren =
  CarerOnboardingRouteRoute._addFileChildren(CarerOnboardingRouteRouteChildren)

interface CarerShiftsRouteChildren {
  CarerShiftsIdRoute: typeof CarerShiftsIdRoute
  CarerShiftsIndexRoute: typeof CarerShiftsIndexRoute
}

const CarerShiftsRouteChildren: CarerShiftsRouteChildren = {
  CarerShiftsIdRoute: CarerShiftsIdRoute,
  CarerShiftsIndexRoute: CarerShiftsIndexRoute,
}

const CarerShiftsRouteWithChildren = CarerShiftsRoute._addFileChildren(
  CarerShiftsRouteChildren,
)

interface CarerRouteRouteChildren {
  CarerOnboardingRouteRoute: typeof CarerOnboardingRouteRouteWithChildren
  CarerAvailabilityRoute: typeof CarerAvailabilityRoute
  CarerDocumentsRoute: typeof CarerDocumentsRoute
  CarerForgotPasswordRoute: typeof CarerForgotPasswordRoute
  CarerLoginRoute: typeof CarerLoginRoute
  CarerProfileRoute: typeof CarerProfileRoute
  CarerShiftsRoute: typeof CarerShiftsRouteWithChildren
  CarerIndexRoute: typeof CarerIndexRoute
  CarerInviteTokenRoute: typeof CarerInviteTokenRoute
  CarerResetPasswordTokenRoute: typeof CarerResetPasswordTokenRoute
}

const CarerRouteRouteChildren: CarerRouteRouteChildren = {
  CarerOnboardingRouteRoute: CarerOnboardingRouteRouteWithChildren,
  CarerAvailabilityRoute: CarerAvailabilityRoute,
  CarerDocumentsRoute: CarerDocumentsRoute,
  CarerForgotPasswordRoute: CarerForgotPasswordRoute,
  CarerLoginRoute: CarerLoginRoute,
  CarerProfileRoute: CarerProfileRoute,
  CarerShiftsRoute: CarerShiftsRouteWithChildren,
  CarerIndexRoute: CarerIndexRoute,
  CarerInviteTokenRoute: CarerInviteTokenRoute,
  CarerResetPasswordTokenRoute: CarerResetPasswordTokenRoute,
}

const CarerRouteRouteWithChildren = CarerRouteRoute._addFileChildren(
  CarerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CarerRouteRoute: CarerRouteRouteWithChildren,
  DocumentsSlugRoute: DocumentsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
