/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CarerRouteRouteImport } from './routes/carer/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarerIndexRouteImport } from './routes/carer/index'
import { Route as DocumentsSlugRouteImport } from './routes/documents.$slug'
import { Route as CarerLoginRouteImport } from './routes/carer/login'
import { Route as CarerForgotPasswordRouteImport } from './routes/carer/forgot-password'
import { Route as CarerDocumentsRouteImport } from './routes/carer/documents'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedShiftsRouteImport } from './routes/_authenticated/shifts'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCentresRouteImport } from './routes/_authenticated/centres'
import { Route as AuthenticatedAvailabilityRouteImport } from './routes/_authenticated/availability'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as CarerOnboardingRouteRouteImport } from './routes/carer/onboarding/route'
import { Route as CarerOnboardingIndexRouteImport } from './routes/carer/onboarding/index'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff.index'
import { Route as AuthenticatedShiftsIndexRouteImport } from './routes/_authenticated/shifts.index'
import { Route as AuthenticatedCentresIndexRouteImport } from './routes/_authenticated/centres.index'
import { Route as CarerOnboardingProfileRouteImport } from './routes/carer/onboarding/profile'
import { Route as CarerOnboardingDocumentsRouteImport } from './routes/carer/onboarding/documents'
import { Route as CarerOnboardingAvailabilityRouteImport } from './routes/carer/onboarding/availability'
import { Route as CarerInviteTokenRouteImport } from './routes/carer/invite.$token'
import { Route as AuthenticatedStaffNewRouteImport } from './routes/_authenticated/staff.new'
import { Route as AuthenticatedStaffImportRouteImport } from './routes/_authenticated/staff.import'
import { Route as AuthenticatedStaffIdRouteImport } from './routes/_authenticated/staff.$id'
import { Route as AuthenticatedShiftsNewRouteImport } from './routes/_authenticated/shifts.new'
import { Route as AuthenticatedShiftsIdRouteImport } from './routes/_authenticated/shifts.$id'
import { Route as AuthenticatedCentresNewRouteImport } from './routes/_authenticated/centres.new'
import { Route as AuthenticatedCentresIdRouteImport } from './routes/_authenticated/centres.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarerRouteRoute = CarerRouteRouteImport.update({
  id: '/carer',
  path: '/carer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarerIndexRoute = CarerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarerRouteRoute,
} as any)
const DocumentsSlugRoute = DocumentsSlugRouteImport.update({
  id: '/documents/$slug',
  path: '/documents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CarerLoginRoute = CarerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CarerRouteRoute,
} as any)
const CarerForgotPasswordRoute = CarerForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => CarerRouteRoute,
} as any)
const CarerDocumentsRoute = CarerDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => CarerRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShiftsRoute = AuthenticatedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCentresRoute = AuthenticatedCentresRouteImport.update({
  id: '/centres',
  path: '/centres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvailabilityRoute =
  AuthenticatedAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const CarerOnboardingRouteRoute = CarerOnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => CarerRouteRoute,
} as any)
const CarerOnboardingIndexRoute = CarerOnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarerOnboardingRouteRoute,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedShiftsIndexRoute =
  AuthenticatedShiftsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedShiftsRoute,
  } as any)
const AuthenticatedCentresIndexRoute =
  AuthenticatedCentresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCentresRoute,
  } as any)
const CarerOnboardingProfileRoute = CarerOnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CarerOnboardingRouteRoute,
} as any)
const CarerOnboardingDocumentsRoute =
  CarerOnboardingDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => CarerOnboardingRouteRoute,
  } as any)
const CarerOnboardingAvailabilityRoute =
  CarerOnboardingAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => CarerOnboardingRouteRoute,
  } as any)
const CarerInviteTokenRoute = CarerInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => CarerRouteRoute,
} as any)
const AuthenticatedStaffNewRoute = AuthenticatedStaffNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedStaffImportRoute =
  AuthenticatedStaffImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffIdRoute = AuthenticatedStaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedShiftsNewRoute = AuthenticatedShiftsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedShiftsRoute,
} as any)
const AuthenticatedShiftsIdRoute = AuthenticatedShiftsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedShiftsRoute,
} as any)
const AuthenticatedCentresNewRoute = AuthenticatedCentresNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedCentresRoute,
} as any)
const AuthenticatedCentresIdRoute = AuthenticatedCentresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCentresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carer': typeof CarerRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/carer/onboarding': typeof CarerOnboardingRouteRouteWithChildren
  '/applications': typeof AuthenticatedApplicationsRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/centres': typeof AuthenticatedCentresRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/shifts': typeof AuthenticatedShiftsRouteWithChildren
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/carer/documents': typeof CarerDocumentsRoute
  '/carer/forgot-password': typeof CarerForgotPasswordRoute
  '/carer/login': typeof CarerLoginRoute
  '/documents/$slug': typeof DocumentsSlugRoute
  '/carer/': typeof CarerIndexRoute
  '/centres/$id': typeof AuthenticatedCentresIdRoute
  '/centres/new': typeof AuthenticatedCentresNewRoute
  '/shifts/$id': typeof AuthenticatedShiftsIdRoute
  '/shifts/new': typeof AuthenticatedShiftsNewRoute
  '/staff/$id': typeof AuthenticatedStaffIdRoute
  '/staff/import': typeof AuthenticatedStaffImportRoute
  '/staff/new': typeof AuthenticatedStaffNewRoute
  '/carer/invite/$token': typeof CarerInviteTokenRoute
  '/carer/onboarding/availability': typeof CarerOnboardingAvailabilityRoute
  '/carer/onboarding/documents': typeof CarerOnboardingDocumentsRoute
  '/carer/onboarding/profile': typeof CarerOnboardingProfileRoute
  '/centres/': typeof AuthenticatedCentresIndexRoute
  '/shifts/': typeof AuthenticatedShiftsIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/carer/onboarding/': typeof CarerOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/users': typeof AuthenticatedUsersRoute
  '/carer/documents': typeof CarerDocumentsRoute
  '/carer/forgot-password': typeof CarerForgotPasswordRoute
  '/carer/login': typeof CarerLoginRoute
  '/documents/$slug': typeof DocumentsSlugRoute
  '/carer': typeof CarerIndexRoute
  '/centres/$id': typeof AuthenticatedCentresIdRoute
  '/centres/new': typeof AuthenticatedCentresNewRoute
  '/shifts/$id': typeof AuthenticatedShiftsIdRoute
  '/shifts/new': typeof AuthenticatedShiftsNewRoute
  '/staff/$id': typeof AuthenticatedStaffIdRoute
  '/staff/import': typeof AuthenticatedStaffImportRoute
  '/staff/new': typeof AuthenticatedStaffNewRoute
  '/carer/invite/$token': typeof CarerInviteTokenRoute
  '/carer/onboarding/availability': typeof CarerOnboardingAvailabilityRoute
  '/carer/onboarding/documents': typeof CarerOnboardingDocumentsRoute
  '/carer/onboarding/profile': typeof CarerOnboardingProfileRoute
  '/centres': typeof AuthenticatedCentresIndexRoute
  '/shifts': typeof AuthenticatedShiftsIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/carer/onboarding': typeof CarerOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/carer': typeof CarerRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/carer/onboarding': typeof CarerOnboardingRouteRouteWithChildren
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/availability': typeof AuthenticatedAvailabilityRoute
  '/_authenticated/centres': typeof AuthenticatedCentresRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/shifts': typeof AuthenticatedShiftsRouteWithChildren
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/carer/documents': typeof CarerDocumentsRoute
  '/carer/forgot-password': typeof CarerForgotPasswordRoute
  '/carer/login': typeof CarerLoginRoute
  '/documents/$slug': typeof DocumentsSlugRoute
  '/carer/': typeof CarerIndexRoute
  '/_authenticated/centres/$id': typeof AuthenticatedCentresIdRoute
  '/_authenticated/centres/new': typeof AuthenticatedCentresNewRoute
  '/_authenticated/shifts/$id': typeof AuthenticatedShiftsIdRoute
  '/_authenticated/shifts/new': typeof AuthenticatedShiftsNewRoute
  '/_authenticated/staff/$id': typeof AuthenticatedStaffIdRoute
  '/_authenticated/staff/import': typeof AuthenticatedStaffImportRoute
  '/_authenticated/staff/new': typeof AuthenticatedStaffNewRoute
  '/carer/invite/$token': typeof CarerInviteTokenRoute
  '/carer/onboarding/availability': typeof CarerOnboardingAvailabilityRoute
  '/carer/onboarding/documents': typeof CarerOnboardingDocumentsRoute
  '/carer/onboarding/profile': typeof CarerOnboardingProfileRoute
  '/_authenticated/centres/': typeof AuthenticatedCentresIndexRoute
  '/_authenticated/shifts/': typeof AuthenticatedShiftsIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/carer/onboarding/': typeof CarerOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carer'
    | '/auth'
    | '/carer/onboarding'
    | '/applications'
    | '/availability'
    | '/centres'
    | '/dashboard'
    | '/profile'
    | '/shifts'
    | '/staff'
    | '/users'
    | '/carer/documents'
    | '/carer/forgot-password'
    | '/carer/login'
    | '/documents/$slug'
    | '/carer/'
    | '/centres/$id'
    | '/centres/new'
    | '/shifts/$id'
    | '/shifts/new'
    | '/staff/$id'
    | '/staff/import'
    | '/staff/new'
    | '/carer/invite/$token'
    | '/carer/onboarding/availability'
    | '/carer/onboarding/documents'
    | '/carer/onboarding/profile'
    | '/centres/'
    | '/shifts/'
    | '/staff/'
    | '/carer/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/applications'
    | '/availability'
    | '/dashboard'
    | '/profile'
    | '/users'
    | '/carer/documents'
    | '/carer/forgot-password'
    | '/carer/login'
    | '/documents/$slug'
    | '/carer'
    | '/centres/$id'
    | '/centres/new'
    | '/shifts/$id'
    | '/shifts/new'
    | '/staff/$id'
    | '/staff/import'
    | '/staff/new'
    | '/carer/invite/$token'
    | '/carer/onboarding/availability'
    | '/carer/onboarding/documents'
    | '/carer/onboarding/profile'
    | '/centres'
    | '/shifts'
    | '/staff'
    | '/carer/onboarding'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/carer'
    | '/auth'
    | '/carer/onboarding'
    | '/_authenticated/applications'
    | '/_authenticated/availability'
    | '/_authenticated/centres'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/shifts'
    | '/_authenticated/staff'
    | '/_authenticated/users'
    | '/carer/documents'
    | '/carer/forgot-password'
    | '/carer/login'
    | '/documents/$slug'
    | '/carer/'
    | '/_authenticated/centres/$id'
    | '/_authenticated/centres/new'
    | '/_authenticated/shifts/$id'
    | '/_authenticated/shifts/new'
    | '/_authenticated/staff/$id'
    | '/_authenticated/staff/import'
    | '/_authenticated/staff/new'
    | '/carer/invite/$token'
    | '/carer/onboarding/availability'
    | '/carer/onboarding/documents'
    | '/carer/onboarding/profile'
    | '/_authenticated/centres/'
    | '/_authenticated/shifts/'
    | '/_authenticated/staff/'
    | '/carer/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CarerRouteRoute: typeof CarerRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DocumentsSlugRoute: typeof DocumentsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carer': {
      id: '/carer'
      path: '/carer'
      fullPath: '/carer'
      preLoaderRoute: typeof CarerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carer/': {
      id: '/carer/'
      path: '/'
      fullPath: '/carer/'
      preLoaderRoute: typeof CarerIndexRouteImport
      parentRoute: typeof CarerRouteRoute
    }
    '/documents/$slug': {
      id: '/documents/$slug'
      path: '/documents/$slug'
      fullPath: '/documents/$slug'
      preLoaderRoute: typeof DocumentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carer/login': {
      id: '/carer/login'
      path: '/login'
      fullPath: '/carer/login'
      preLoaderRoute: typeof CarerLoginRouteImport
      parentRoute: typeof CarerRouteRoute
    }
    '/carer/forgot-password': {
      id: '/carer/forgot-password'
      path: '/forgot-password'
      fullPath: '/carer/forgot-password'
      preLoaderRoute: typeof CarerForgotPasswordRouteImport
      parentRoute: typeof CarerRouteRoute
    }
    '/carer/documents': {
      id: '/carer/documents'
      path: '/documents'
      fullPath: '/carer/documents'
      preLoaderRoute: typeof CarerDocumentsRouteImport
      parentRoute: typeof CarerRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shifts': {
      id: '/_authenticated/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthenticatedShiftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/centres': {
      id: '/_authenticated/centres'
      path: '/centres'
      fullPath: '/centres'
      preLoaderRoute: typeof AuthenticatedCentresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/availability': {
      id: '/_authenticated/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AuthenticatedAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/carer/onboarding': {
      id: '/carer/onboarding'
      path: '/onboarding'
      fullPath: '/carer/onboarding'
      preLoaderRoute: typeof CarerOnboardingRouteRouteImport
      parentRoute: typeof CarerRouteRoute
    }
    '/carer/onboarding/': {
      id: '/carer/onboarding/'
      path: '/'
      fullPath: '/carer/onboarding/'
      preLoaderRoute: typeof CarerOnboardingIndexRouteImport
      parentRoute: typeof CarerOnboardingRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/shifts/': {
      id: '/_authenticated/shifts/'
      path: '/'
      fullPath: '/shifts/'
      preLoaderRoute: typeof AuthenticatedShiftsIndexRouteImport
      parentRoute: typeof AuthenticatedShiftsRoute
    }
    '/_authenticated/centres/': {
      id: '/_authenticated/centres/'
      path: '/'
      fullPath: '/centres/'
      preLoaderRoute: typeof AuthenticatedCentresIndexRouteImport
      parentRoute: typeof AuthenticatedCentresRoute
    }
    '/carer/onboarding/profile': {
      id: '/carer/onboarding/profile'
      path: '/profile'
      fullPath: '/carer/onboarding/profile'
      preLoaderRoute: typeof CarerOnboardingProfileRouteImport
      parentRoute: typeof CarerOnboardingRouteRoute
    }
    '/carer/onboarding/documents': {
      id: '/carer/onboarding/documents'
      path: '/documents'
      fullPath: '/carer/onboarding/documents'
      preLoaderRoute: typeof CarerOnboardingDocumentsRouteImport
      parentRoute: typeof CarerOnboardingRouteRoute
    }
    '/carer/onboarding/availability': {
      id: '/carer/onboarding/availability'
      path: '/availability'
      fullPath: '/carer/onboarding/availability'
      preLoaderRoute: typeof CarerOnboardingAvailabilityRouteImport
      parentRoute: typeof CarerOnboardingRouteRoute
    }
    '/carer/invite/$token': {
      id: '/carer/invite/$token'
      path: '/invite/$token'
      fullPath: '/carer/invite/$token'
      preLoaderRoute: typeof CarerInviteTokenRouteImport
      parentRoute: typeof CarerRouteRoute
    }
    '/_authenticated/staff/new': {
      id: '/_authenticated/staff/new'
      path: '/new'
      fullPath: '/staff/new'
      preLoaderRoute: typeof AuthenticatedStaffNewRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/import': {
      id: '/_authenticated/staff/import'
      path: '/import'
      fullPath: '/staff/import'
      preLoaderRoute: typeof AuthenticatedStaffImportRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/$id': {
      id: '/_authenticated/staff/$id'
      path: '/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof AuthenticatedStaffIdRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/shifts/new': {
      id: '/_authenticated/shifts/new'
      path: '/new'
      fullPath: '/shifts/new'
      preLoaderRoute: typeof AuthenticatedShiftsNewRouteImport
      parentRoute: typeof AuthenticatedShiftsRoute
    }
    '/_authenticated/shifts/$id': {
      id: '/_authenticated/shifts/$id'
      path: '/$id'
      fullPath: '/shifts/$id'
      preLoaderRoute: typeof AuthenticatedShiftsIdRouteImport
      parentRoute: typeof AuthenticatedShiftsRoute
    }
    '/_authenticated/centres/new': {
      id: '/_authenticated/centres/new'
      path: '/new'
      fullPath: '/centres/new'
      preLoaderRoute: typeof AuthenticatedCentresNewRouteImport
      parentRoute: typeof AuthenticatedCentresRoute
    }
    '/_authenticated/centres/$id': {
      id: '/_authenticated/centres/$id'
      path: '/$id'
      fullPath: '/centres/$id'
      preLoaderRoute: typeof AuthenticatedCentresIdRouteImport
      parentRoute: typeof AuthenticatedCentresRoute
    }
  }
}

interface AuthenticatedCentresRouteChildren {
  AuthenticatedCentresIdRoute: typeof AuthenticatedCentresIdRoute
  AuthenticatedCentresNewRoute: typeof AuthenticatedCentresNewRoute
  AuthenticatedCentresIndexRoute: typeof AuthenticatedCentresIndexRoute
}

const AuthenticatedCentresRouteChildren: AuthenticatedCentresRouteChildren = {
  AuthenticatedCentresIdRoute: AuthenticatedCentresIdRoute,
  AuthenticatedCentresNewRoute: AuthenticatedCentresNewRoute,
  AuthenticatedCentresIndexRoute: AuthenticatedCentresIndexRoute,
}

const AuthenticatedCentresRouteWithChildren =
  AuthenticatedCentresRoute._addFileChildren(AuthenticatedCentresRouteChildren)

interface AuthenticatedShiftsRouteChildren {
  AuthenticatedShiftsIdRoute: typeof AuthenticatedShiftsIdRoute
  AuthenticatedShiftsNewRoute: typeof AuthenticatedShiftsNewRoute
  AuthenticatedShiftsIndexRoute: typeof AuthenticatedShiftsIndexRoute
}

const AuthenticatedShiftsRouteChildren: AuthenticatedShiftsRouteChildren = {
  AuthenticatedShiftsIdRoute: AuthenticatedShiftsIdRoute,
  AuthenticatedShiftsNewRoute: AuthenticatedShiftsNewRoute,
  AuthenticatedShiftsIndexRoute: AuthenticatedShiftsIndexRoute,
}

const AuthenticatedShiftsRouteWithChildren =
  AuthenticatedShiftsRoute._addFileChildren(AuthenticatedShiftsRouteChildren)

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffIdRoute: typeof AuthenticatedStaffIdRoute
  AuthenticatedStaffImportRoute: typeof AuthenticatedStaffImportRoute
  AuthenticatedStaffNewRoute: typeof AuthenticatedStaffNewRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffIdRoute: AuthenticatedStaffIdRoute,
  AuthenticatedStaffImportRoute: AuthenticatedStaffImportRoute,
  AuthenticatedStaffNewRoute: AuthenticatedStaffNewRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedAvailabilityRoute: typeof AuthenticatedAvailabilityRoute
  AuthenticatedCentresRoute: typeof AuthenticatedCentresRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedShiftsRoute: typeof AuthenticatedShiftsRouteWithChildren
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedAvailabilityRoute: AuthenticatedAvailabilityRoute,
  AuthenticatedCentresRoute: AuthenticatedCentresRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedShiftsRoute: AuthenticatedShiftsRouteWithChildren,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CarerOnboardingRouteRouteChildren {
  CarerOnboardingAvailabilityRoute: typeof CarerOnboardingAvailabilityRoute
  CarerOnboardingDocumentsRoute: typeof CarerOnboardingDocumentsRoute
  CarerOnboardingProfileRoute: typeof CarerOnboardingProfileRoute
  CarerOnboardingIndexRoute: typeof CarerOnboardingIndexRoute
}

const CarerOnboardingRouteRouteChildren: CarerOnboardingRouteRouteChildren = {
  CarerOnboardingAvailabilityRoute: CarerOnboardingAvailabilityRoute,
  CarerOnboardingDocumentsRoute: CarerOnboardingDocumentsRoute,
  CarerOnboardingProfileRoute: CarerOnboardingProfileRoute,
  CarerOnboardingIndexRoute: CarerOnboardingIndexRoute,
}

const CarerOnboardingRouteRouteWithChildren =
  CarerOnboardingRouteRoute._addFileChildren(CarerOnboardingRouteRouteChildren)

interface CarerRouteRouteChildren {
  CarerOnboardingRouteRoute: typeof CarerOnboardingRouteRouteWithChildren
  CarerDocumentsRoute: typeof CarerDocumentsRoute
  CarerForgotPasswordRoute: typeof CarerForgotPasswordRoute
  CarerLoginRoute: typeof CarerLoginRoute
  CarerIndexRoute: typeof CarerIndexRoute
  CarerInviteTokenRoute: typeof CarerInviteTokenRoute
}

const CarerRouteRouteChildren: CarerRouteRouteChildren = {
  CarerOnboardingRouteRoute: CarerOnboardingRouteRouteWithChildren,
  CarerDocumentsRoute: CarerDocumentsRoute,
  CarerForgotPasswordRoute: CarerForgotPasswordRoute,
  CarerLoginRoute: CarerLoginRoute,
  CarerIndexRoute: CarerIndexRoute,
  CarerInviteTokenRoute: CarerInviteTokenRoute,
}

const CarerRouteRouteWithChildren = CarerRouteRoute._addFileChildren(
  CarerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CarerRouteRoute: CarerRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DocumentsSlugRoute: DocumentsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
