export const PLATFORM_AUDIT_ACTOR_TYPES = ['ops_user', 'system'] as const;
export type PlatformAuditActorType = (typeof PLATFORM_AUDIT_ACTOR_TYPES)[number];

export const PLATFORM_AUDIT_ENTITY_TYPES = [
  'shift',
  'centre',
  'user',
  'staff',
  'system',
] as const;
export type PlatformAuditEntityType = (typeof PLATFORM_AUDIT_ENTITY_TYPES)[number];

export const PLATFORM_AUDIT_ACTIONS = {
  shiftCreated: 'shift_created',
  shiftUpdated: 'shift_updated',
  shiftAssigned: 'shift_assigned',
  shiftUnassigned: 'shift_unassigned',
  shiftReassigned: 'shift_reassigned',
  shiftCancelled: 'shift_cancelled',
  shiftCompletedManual: 'shift_completed_manual',
  shiftCompletedAuto: 'shift_completed_auto',
  shiftUpdateCommunicationSent: 'shift_update_communication_sent',
  shiftUpdateCommunicationFailed: 'shift_update_communication_failed',
  shiftAvailabilityOverrideConfirmed: 'shift_availability_override_confirmed',
  shiftStaffUnassignedScheduleChange: 'shift_staff_unassigned_schedule_change',
  batchProgressEmailScheduled: 'batch_progress_email_scheduled',
  batchProgressEmailBlocked: 'batch_progress_email_blocked',
  batchRequestCompleted: 'batch_request_completed',
  batchFinalConfirmationScheduled: 'batch_final_confirmation_scheduled',
  batchConfirmationOutdated: 'batch_confirmation_outdated',
  batchUpdateConfirmationScheduled: 'batch_update_confirmation_scheduled',
  batchRequestCancelled: 'batch_request_cancelled',
  batchCancellationCentreScheduled: 'batch_cancellation_centre_scheduled',
  batchCancellationCarerScheduled: 'batch_cancellation_carer_scheduled',
  centreCreated: 'centre_created',
  centreUpdated: 'centre_updated',
  centreDeleted: 'centre_deleted',
  userInvited: 'user_invited',
  userUpdated: 'user_updated',
  userPasswordReset: 'user_password_reset',
  userPasswordChanged: 'user_password_changed',
  staffUpdated: 'staff_updated',
  staffDeleted: 'staff_deleted',
} as const;

export type PlatformAuditAction =
  (typeof PLATFORM_AUDIT_ACTIONS)[keyof typeof PLATFORM_AUDIT_ACTIONS];

const ACTION_ENTITY: Record<PlatformAuditAction, PlatformAuditEntityType> = {
  shift_created: 'shift',
  shift_updated: 'shift',
  shift_assigned: 'shift',
  shift_unassigned: 'shift',
  shift_reassigned: 'shift',
  shift_cancelled: 'shift',
  shift_completed_manual: 'shift',
  shift_completed_auto: 'shift',
  shift_update_communication_sent: 'shift',
  shift_update_communication_failed: 'shift',
  shift_availability_override_confirmed: 'shift',
  shift_staff_unassigned_schedule_change: 'shift',
  batch_progress_email_scheduled: 'centre',
  batch_progress_email_blocked: 'centre',
  batch_request_completed: 'centre',
  batch_final_confirmation_scheduled: 'centre',
  batch_confirmation_outdated: 'centre',
  batch_update_confirmation_scheduled: 'centre',
  batch_request_cancelled: 'centre',
  batch_cancellation_centre_scheduled: 'centre',
  batch_cancellation_carer_scheduled: 'centre',
  centre_created: 'centre',
  centre_updated: 'centre',
  centre_deleted: 'centre',
  user_invited: 'user',
  user_updated: 'user',
  user_password_reset: 'user',
  user_password_changed: 'user',
  staff_updated: 'staff',
  staff_deleted: 'staff',
};

export function defaultEntityTypeForAction(action: PlatformAuditAction): PlatformAuditEntityType {
  return ACTION_ENTITY[action];
}

/** Allowed metadata keys for platform audit events. */
export const PLATFORM_AUDIT_METADATA_ALLOWLIST = new Set([
  'changes',
  'previousStaffId',
  'newStaffId',
  'assignedStaffId',
  'cancellationReasonPreview',
  'shiftDate',
  'startTime',
  'endTime',
  'centreName',
  'source',
  'role',
  'isActive',
  'email',
  'name',
  'forced',
  'recipientType',
  'recipientEmail',
  'includedChanges',
  'deliveryMessageId',
  'failureCode',
  'failureReason',
  'eligibilityReasons',
  'batchId',
  'fulfilledCount',
  'activeTotal',
  'scheduledCommunicationId',
  'changeKind',
  'pendingChangeRevision',
  'confirmationRevision',
  'selectedChangeIds',
  'highlightedChanges',
  'cancelCase',
  'recipients',
  'cancelledChildCount',
  'source',
]);
